name: .NET Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Ensure browsers are installed
        run: pwsh ./test/PlaywrightTests/bin/Debug/net8.0/playwright.ps1 install --with-deps
        timeout-minutes: 5

      - name: Test
        env:
          ASPNETCORE_ENVIRONMENT: Production
          GitHub__ClientId: ${{ secrets.GITHUBCLIENTID }}
          GitHub__ClientSecret: ${{ secrets.GITHUBCLIENTSECRET }}
        run: dotnet test --no-build --verbosity normal