name: .NET Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Install PowerShell Core
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/20.04/prod.list" -O /etc/apt/sources.list.d/microsoft-prod.list
          wget -q "https://packages.microsoft.com/keys/microsoft.asc" -O- | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y powershell

          pwsh --version

      - name: Install Playwright browsers
        run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
          
      - name: Test
        env:
          ASPNETCORE_ENVIRONMENT: Production
          GitHub__ClientId: ${{ secrets.GITHUBCLIENTID }}
          GitHub__ClientSecret: ${{ secrets.GITHUBCLIENTSECRET }}
        run: dotnet test --no-build --verbosity normal