name: .NET Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Install Playwright browsers
        run: |
          pwd 
          ls 
          cd test/PlaywrightTests
          pwd
          ls
          pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

      - name: Build
        run: dotnet build

      - name: Test
        env:
          ASPNETCORE_ENVIRONMENT: Production
          GitHub__ClientId: ${{ secrets.GITHUBCLIENTID }}
          GitHub__ClientSecret: ${{ secrets.GITHUBCLIENTSECRET }}
        run: dotnet test --no-build --verbosity normal