# Documentation:
# 
# https://docs.github.com/en/enterprise-server@3.14/actions/use-cases-and-examples/project-management/moving-assigned-issues-on-project-boards

name: Move assigned card

on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: ITU-BDSA2024-GROUP18 Chirp
          column: In Progress
          repo-token: ${{ secrets.MOVE_SECRET }}