name: Build and Release Chirp

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux-x64, osx-x64, win-x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install dependencies for Chirp.CLI
        run: dotnet restore src/Chirp.CLI/Chirp.CLI.csproj

      - name: Install dependencies for SimpleDb
        run: dotnet restore src/SimpleDb/SimpleDb.csproj

      - name: Build Chirp.CLI executable
        run: dotnet publish src/Chirp.CLI/Chirp.CLI.csproj -c Release -r ${{ matrix.os }} --self-contained false

      - name: List publish directory for debugging
        run: ls -R src/Chirp.CLI/bin/Release/net7.0/${{ matrix.os }}

      - name: Create ZIP archive
        run: |
          zip -r chirp-${{ matrix.os }}.zip src/Chirp.CLI/bin/Release/net7.0/${{ matrix.os }}/publish

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            chirp-linux-x64.zip   # Updated from chirp-ubuntu-latest.zip
            chirp-osx-x64.zip     # Updated from chirp-macos-latest.zip
            chirp-win-x64.zip     # Updated from chirp-windows-latest.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}